In [1]:
import pandas as pd
import numpy as np
import os

## Dataset information

In [2]:
dataset = pd.read_csv("data/resume_data.csv")

In [3]:
dataset.head()

,address,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,...,online_links,issue_dates,expiry_dates,﻿job_position_name,educationaL_requirements,experiencere_requirement,age_requirement,responsibilities.1,skills_required,matched_score
0,NaN,Big data analytics working and database wareho...,"['Big Data', 'Hadoop', 'Hive', 'Python', 'Mapr...",['The Amity School of Engineering & Technology...,['B.Tech'],['2019'],['N/A'],[None],['Electronics'],['Coca-COla'],...,NaN,NaN,NaN,Senior Software Engineer,B.Sc in Computer Science & Engineering from a ...,At least 1 year,NaN,Technical Support\nTroubleshooting\nCollaborat...,NaN,0.850000
1,NaN,Fresher looking to join as a data analyst and ...,"['Data Analysis', 'Data Analytics', 'Business ...","['Delhi University - Hansraj College', 'Delhi ...","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)']","['2015', '2018']","['N/A', 'N/A']","['N/A', 'N/A']","['Mathematics', 'Statistics']",['BIB Consultancy'],...,NaN,NaN,NaN,Machine Learning (ML) Engineer,M.Sc in Computer Science & Engineering or in a...,At least 5 year(s),NaN,Machine Learning Leadership\nCross-Functional ...,NaN,0.750000
2,NaN,NaN,"['Software Development', 'Machine Learning', '...","['Birla Institute of Technology (BIT), Ranchi']",['B.Tech'],['2018'],['N/A'],['N/A'],['Electronics/Telecommunication'],['Axis Bank Limited'],...,NaN,NaN,NaN,"Executive/ Senior Executive- Trade Marketing, ...",Master of Business Administration (MBA),At least 3 years,NaN,"Trade Marketing Executive\nBrand Visibility, S...",Brand Promotion\nCampaign Management\nField Su...,0.416667
3,NaN,To obtain a position in a fast-paced business ...,"['accounts payables', 'accounts receivables', ...","['Martinez Adult Education, Business Training ...",['Computer Applications Specialist Certificate...,['2008'],[None],[None],['Computer Applications'],"['Company Name ï¼ City , State', 'Company Name...",...,NaN,NaN,NaN,Business Development Executive,Bachelor/Honors,1 to 3 years,Age 22 to 30 years,Apparel Sourcing\nQuality Garment Sourcing\nRe...,Fast typing skill\nIELTSInternet browsing & on...,0.760000
4,NaN,Professional accountant with an outstanding wo...,"['Analytical reasoning', 'Compliance testing k...",['Kent State University'],['Bachelor of Business Administration'],[None],['3.84'],[None],['Accounting'],"['Company Name', 'Company Name', 'Company Name...",...,[None],[None],"['February 15, 2021']",Senior iOS Engineer,Bachelor of Science (BSc) in Computer Science,At least 4 years,NaN,iOS Lifecycle\nRequirement Analysis\nNative Fr...,iOS\niOS App Developer\niOS Application Develo...,0.650000

In [4]:
dataset.columns

Index(['address', 'career_objective', 'skills', 'educational_institution_name',
       'degree_names', 'passing_years', 'educational_results', 'result_types',
       'major_field_of_studies', 'professional_company_names', 'company_urls',
       'start_dates', 'end_dates', 'related_skils_in_job', 'positions',
       'locations', 'responsibilities', 'extra_curricular_activity_types',
       'extra_curricular_organization_names',
       'extra_curricular_organization_links', 'role_positions', 'languages',
       'proficiency_levels', 'certification_providers', 'certification_skills',
       'online_links', 'issue_dates', 'expiry_dates', '﻿job_position_name',
       'educationaL_requirements', 'experiencere_requirement',
       'age_requirement', 'responsibilities.1', 'skills_required',
       'matched_score'],
      dtype='str')

In [5]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 9544 entries, 0 to 9543
Data columns (total 35 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   address                              784 non-null    str
 1   career_objective                     4740 non-null   str
 2   skills                               9488 non-null   str
 3   educational_institution_name         9460 non-null   str
 4   degree_names                         9460 non-null   str
 5   passing_years                        9460 non-null   str
 6   educational_results                  9460 non-null   str
 7   result_types                         9460 non-null   str
 8   major_field_of_studies               9460 non-null   str
 9   professional_company_names           9460 non-null   str
 10  company_urls                         9460 non-null   str
 11  start_dates                          9460 non-null   str
 12  end_dates                            9460 non-null   str
 13  related_skils_in_job                 9460 non-null   str
 14  positions                            9460 non-null   str
 15  locations                            9460 non-null   str
 16  responsibilities                     9544 non-null   str
 17  extra_curricular_activity_types      3426 non-null   str
 18  extra_curricular_organization_names  3426 non-null   str
 19  extra_curricular_organization_links  3426 non-null   str
 20  role_positions                       3426 non-null   str
 21  languages                            700 non-null    str
 22  proficiency_levels                   700 non-null    str
 23  certification_providers              2008 non-null   str
 24  certification_skills                 2008 non-null   str
 25  online_links                         2008 non-null   str
 26  issue_dates                          2008 non-null   str
 27  expiry_dates                         2008 non-null   str
 28  ﻿job_position_name                   9544 non-null   str
 29  educationaL_requirements             9544 non-null   str
 30  experiencere_requirement             8180 non-null   str
 31  age_requirement                      5457 non-null   str
 32  responsibilities.1                   9544 non-null   str
 33  skills_required                      7843 non-null   str
 34  matched_score                        9544 non-null   float64
dtypes: float64(1), str(34)
memory usage: 2.5 MB

In [6]:
dataset.shape

(9544, 35)

## Cleaning the columns

In [7]:
print(dataset["﻿job_position_name"].value_counts())

job_position_name
Project Coordinator (Civil)                                                                342
HR Officer                                                                                 342
Civil Engineer                                                                             342
Site Engineer                                                                              342
Senior Software Engineer                                                                   341
Executive/ Senior Executive- Trade Marketing, Hygiene Products                             341
Business Development Executive                                                             341
AI Engineer                                                                                341
Mechanical Engineer                                                                        341
Mechanical Designer                                                                        341
Asst. Manager/ Manger (Administrative)                                                     341
Database Administrator (DBA)                                                               341
System Administrator (Operation & Maintenance of Server, Storage & Service Desk System)    341
Network Support Engineer                                                                   341
Executive - VAT                                                                            341
Sr.Officer / Executive - Internal Audit                                                    341
Management Trainee - Mechanical                                                            341
Head of Internal Control & Compliance (ICC) - SEVP/DMD                                     341
Manager- Human Resource Management (HRM)\n                                                 341
Marketing Officer                                                                          341
Machine Learning (ML) Engineer                                                             340
Senior iOS Engineer                                                                        340
Executive/ Sr. Executive -IT                                                               340
Intern (Generative AI Engineering - 2D/3D Image Generation)                                340
DevOps Engineer                                                                            340
Data Engineer                                                                              340
Full Stack Developer (Python,React js)                                                     340
Data Science Engineer                                                                      340
Name: count, dtype: int64

In [8]:
dataset.columns = dataset.columns.str.strip()

dataset.columns = dataset.columns.str.replace(r"[﻿1./]", "", regex=True)

dataset.columns = dataset.columns.str.replace(" ","", regex=True)

dataset.columns = dataset.columns.str.lower()

In [9]:
dataset.columns.tolist()

['address',
 'career_objective',
 'skills',
 'educational_institution_name',
 'degree_names',
 'passing_years',
 'educational_results',
 'result_types',
 'major_field_of_studies',
 'professional_company_names',
 'company_urls',
 'start_dates',
 'end_dates',
 'related_skils_in_job',
 'positions',
 'locations',
 'responsibilities',
 'extra_curricular_activity_types',
 'extra_curricular_organization_names',
 'extra_curricular_organization_links',
 'role_positions',
 'languages',
 'proficiency_levels',
 'certification_providers',
 'certification_skills',
 'online_links',
 'issue_dates',
 'expiry_dates',
 'job_position_name',
 'educational_requirements',
 'experiencere_requirement',
 'age_requirement',
 'responsibilities',
 'skills_required',
 'matched_score']

In [10]:
drop_cols = [
    "online_links",
    "extra_curricular_organization_names",
    "extra_curricular_organization_links",
    "address",
    "company_urls",
    "issue_dates",
    "expiry_dates",
    "locations",
]

dataset = dataset.drop(columns=drop_cols)

In [11]:
dataset.columns.tolist()

['career_objective',
 'skills',
 'educational_institution_name',
 'degree_names',
 'passing_years',
 'educational_results',
 'result_types',
 'major_field_of_studies',
 'professional_company_names',
 'start_dates',
 'end_dates',
 'related_skils_in_job',
 'positions',
 'responsibilities',
 'extra_curricular_activity_types',
 'role_positions',
 'languages',
 'proficiency_levels',
 'certification_providers',
 'certification_skills',
 'job_position_name',
 'educational_requirements',
 'experiencere_requirement',
 'age_requirement',
 'responsibilities',
 'skills_required',
 'matched_score']

In [12]:
dataset = dataset.fillna("")

In [13]:
import re

def clean_text(text):

    text = str(text)

    text = re.sub(r"\[|\]|'", " ", text)

    text = re.sub(r"\bnone\b", " ", text)

    text = re.sub(r"[^a-zA-Z ]", " ", text)

    text = re.sub(r"\s+", " ", text)

    return text.strip().lower()

In [14]:
dataset = dataset.apply(
    lambda col: col.map(clean_text)
)

In [15]:
dataset = dataset.replace(r"\bnone\b", "", regex=True)

In [16]:
resume = dataset[['career_objective',
 'skills',
 'educational_institution_name',
 'degree_names',
 'passing_years',
 'educational_results',
 'result_types',
 'major_field_of_studies',
 'professional_company_names',
 'start_dates',
 'end_dates',
 'related_skils_in_job',
 'positions',
 'responsibilities',
 'extra_curricular_activity_types',
 'role_positions',
 'languages',
 'proficiency_levels',
 'certification_providers',
 'certification_skills',
]]

In [17]:
job = dataset[['job_position_name',
 'educational_requirements',
 'experiencere_requirement',
 'age_requirement',
 'responsibilities',
 'skills_required']]

In [18]:
resume.head()

,career_objective,skills,educational_institution_name,degree_names,passing_years,educational_results,result_types,major_field_of_studies,professional_company_names,start_dates,...,related_skils_in_job,positions,responsibilities,responsibilities,extra_curricular_activity_types,role_positions,languages,proficiency_levels,certification_providers,certification_skills
0,big data analytics working and database wareho...,big data hadoop hive python mapreduce spark ja...,the amity school of engineering technology ase...,b tech,,n a,,electronics,coca cola,nov,...,big data,big data analyst,technical support troubleshooting collaboratio...,technical support troubleshooting collaboratio...,,,,,,
1,fresher looking to join as a data analyst and ...,data analysis data analytics business analysis...,delhi university hansraj college delhi univers...,b sc maths m sc science statistics,,n a n a,n a n a,mathematics statistics,bib consultancy,sep,...,data analysis business analysis machine learning,business analyst,machine learning leadership cross functional c...,machine learning leadership cross functional c...,,,,,,
2,,software development machine learning deep lea...,birla institute of technology bit ranchi,b tech,,n a,n a,electronics telecommunication,axis bank limited,june,...,unified payment interface risk prediction big ...,software developer machine learning engineer,trade marketing executive brand visibility sal...,trade marketing executive brand visibility sal...,,,,,,
3,to obtain a position in a fast paced business ...,accounts payables accounts receivables account...,martinez adult education business training cen...,computer applications specialist certificate p...,,,,computer applications,company name city state company name city stat...,january january january january january n a,...,accounts receivables banking g l accounts acco...,accountant accounts receivable clerk mortgage ...,apparel sourcing quality garment sourcing reli...,apparel sourcing quality garment sourcing reli...,,,,,,
4,professional accountant with an outstanding wo...,analytical reasoning compliance testing knowle...,kent state university,bachelor of business administration,,,,accounting,company name company name company name company...,january january january january january,...,collections accounts receivable financial repo...,staff accountant senior accountant tax analyst...,ios lifecycle requirement analysis native fram...,ios lifecycle requirement analysis native fram...,professional organization honor society honor ...,,,,ohio notary public,

In [19]:
job.head()

,job_position_name,educational_requirements,experiencere_requirement,age_requirement,responsibilities,responsibilities,skills_required
0,senior software engineer,b sc in computer science engineering from a re...,at least year,,technical support troubleshooting collaboratio...,technical support troubleshooting collaboratio...,
1,machine learning ml engineer,m sc in computer science engineering or in any...,at least year s,,machine learning leadership cross functional c...,machine learning leadership cross functional c...,
2,executive senior executive trade marketing hyg...,master of business administration mba,at least years,,trade marketing executive brand visibility sal...,trade marketing executive brand visibility sal...,brand promotion campaign management field supe...
3,business development executive,bachelor honors,to years,age to years,apparel sourcing quality garment sourcing reli...,apparel sourcing quality garment sourcing reli...,fast typing skill ieltsinternet browsing onlin...
4,senior ios engineer,bachelor of science bsc in computer science,at least years,,ios lifecycle requirement analysis native fram...,ios lifecycle requirement analysis native fram...,ios ios app developer ios application developm...

## Text Preprocessing

In [20]:
import nltk
nltk.download("punkt")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to /Users/vijais/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/vijais/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/vijais/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/vijais/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [21]:
resume["resume_text"] = resume.astype(str).agg(" ".join, axis=1)

In [22]:
job["job_text"] = job.astype(str).agg(" ".join, axis=1)

In [29]:
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [30]:
def preprocess_text(text):
    sentences = sent_tokenize(text)
    for sentence in sentences:
        words = word_tokenize(sentence)
        # Further preprocessing steps can be added here
        words = [word for word in words if word not in stopwords.words("english")]
        words = [WordNetLemmatizer().lemmatize(word) for word in words]
        sentences = " ".join(words)
    return sentences

In [31]:
resume["resume_text_processed"]= resume["resume_text"].apply(preprocess_text)
job["job_text_processed"]= job["job_text"].apply(preprocess_text)

In [32]:
resume_data=resume[["resume_text_processed"]]
job_data=job[["job_text_processed"]]

In [33]:
resume_data.to_csv("data/resume_data_processed.csv", index=False)
job_data.to_csv("data/job_data_processed.csv", index=False)

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer